baseURL = "/"
languageCode = "en-us"
title = "Demo Hugo Website"
theme = ""
summaryLength = "20"
paginate = 6
disqusShortname = "adrian"
googleAnalytics = ""

[outputs]
home = [ "HTML" ]

[taxonomies]
category = "categories"
color = "colors"
size = "sizes"

[params]
logo = "images/logo.png"
home = "Home"
description = "I changed the meta data. This is new meta data"
author = "Farhad Hossen"
snipcartAPI = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
currency = "$"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
googleAnalitycsID = "Your ID"
mobile = "01832944423"
email = "fake@gmail.com"
location = "Los Angeles, USA"
contactFormAction = "#"
footer_content = "This is demo footer content. This will goes to under the logo"
copyright = "copyright all right reserved [demosite.com](https://themefisher.com/)"

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"

[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.1.0/default/snipcart.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/SyoTimer/jquery.syotimer.min.js"

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.1.0/default/snipcart.js"

[[params.plugins.js]]
link = "plugins/instafeed-js/instafeed.min.js"

[[params.plugins.js]]
link = "plugins/search/fuse.min.js"

[[params.plugins.js]]
link = "plugins/search/mark.js"

[[params.plugins.js]]
link = "plugins/search/search.js"

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

  [params.preloader]
  enable = true
  preloader = ""

  [params.search]
  enable = true

[[menu.main]]
name = "Shop"
URL = "shop"
weight = 1
hasChildren = true

[[menu.main]]
parent = "Shop"
name = "Item 1"
url = "https://gethugothemes.com/"
weight = 1

[[menu.main]]
parent = "Shop"
name = "Item 2"
url = "https://gethugothemes.com/"
weight = 2

[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Faq"
URL = "faq"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.category]]
name = "Bag"
URL = "categories/bag"
weight = 1

[[menu.category]]
name = "Shirt"
URL = "categories/shirt"
weight = 2

[[menu.category]]
name = "Shoe"
URL = "categories/shoe"
weight = 3

[[menu.category]]
name = "Tops"
URL = "categories/tops"
weight = 4

[[menu.useful_links]]
name = "Shop"
URL = "shop"
weight = 1

[[menu.useful_links]]
name = "About"
URL = "about"
weight = 2

[[menu.useful_links]]
name = "Faq"
URL = "faq"
weight = 3

[[menu.useful_links]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 1

[[menu.footer]]
name = "Terms & Conditions"
URL = "terms-conditions"
weight = 2

[[menu.footer]]
name = "Cookie Policy"
URL = "cookie-policy"
weight = 3

[[menu.footer]]
name = "Terms of Sale"
URL = "terms-of-sale"
weight = 4
